name: admin_desktop
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  intl: ^0.20.2
  msix: ^3.16.9
  lottie: ^3.3.0
  get_it: ^7.7.0
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  provider: ^6.1.5
  fl_chart: ^1.0.0
  auto_route: ^10.1.0+1
  geolocator: ^14.0.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  dotted_border: ^2.1.0
  osm_nominatim: ^3.0.1
  flutter_remix: ^0.0.3
  image_cropper: ^9.1.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.2.0
  multi_dropdown: ^3.0.1
  auto_size_text: ^3.0.0
  flutter_isolate: ^2.1.0
  pull_to_refresh: ^2.0.0
  bitsdojo_window: ^0.1.6
  flutter_slidable: ^4.0.0
  flutter_riverpod: ^2.6.1
  connectivity_plus: ^6.0.5
  package_info_plus: ^8.3.1
  percent_indicator: ^4.2.5
  freezed_annotation: ^2.4.4
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.12.2
  drag_and_drop_lists: ^0.4.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.3.1
  proste_indexed_stack: ^0.2.4
  calendar_date_picker2: ^2.0.1
  flutter_esc_pos_utils: ^1.0.1
  flutter_advanced_switch: ^3.1.0
  flutter_staggered_animations: ^1.1.1
  ping_discover_network_forked: ^0.0.1
  audioplayers: ^6.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_pos_printer_platform_image_3:
    path: packages/flutter_pos_printer_platform_image_3

  #firebase:
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  firebase_messaging: ^16.1.0
  firebase_analytics: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.9
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.3
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  mocktail: ^1.0.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/png/app_logo.png"
  adaptive_icon_foreground: "assets/images/png/app_logo.png"
  adaptive_icon_background: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/png/app_logo.png"
  macos:
    generate: true
    image_path: "assets/images/png/app_logo.png"

  msix_config:
    display_name: Grooops POS App
    publisher_display_name: Grooops
    identity_name: my.com.grooops.pos
    msix_version: 1.0.0.0
    logo_path: D:\post_app_foodyman-main\post_app_foodyman\assets\images\png\app_logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/svg/
    - assets/lottie/
    - assets/
    - assets/images/
    - assets/audio/
