analyzer:
  exclude:
    - example/**
    - test/**
  errors:
    deprecated_member_use: ignore
    unreachable_switch_default: ignore
    unused_element_parameter: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
